### ISSUE TITLE
Add St Andrews PhD theses

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#116]
See https://research-repository.st-andrews.ac.uk/handle/10023/99 and check what's missing in the bibliography.

**Comment by ruthhoffmann** [comment]
@alex-konovalov I believe you might have missed out my thesis that cites GAP http://hdl.handle.net/10023/7034 .

**Comment by alex-konovalov** [comment]
Thanks - will do!

**Comment by alex-konovalov** [comment]
Found the reason - it was overlooked because @ruthhoffmann is in Computer Science collection, and I looked only at Pure Maths one. 

I have examined also https://research-repository.st-andrews.ac.uk/handle/10023/60 and discovered more:
- @ruthhoffmann https://research-repository.st-andrews.ac.uk/handle/10023/7034
- Andy Grayland https://research-repository.st-andrews.ac.uk/handle/10023/1718
- Björn Assmann https://research-repository.st-andrews.ac.uk/handle/10023/435 
- Iain McDonald https://research-repository.st-andrews.ac.uk/handle/10023/14983 

Are there any other collections which may have GAP?

**Comment by ruthhoffmann** [comment]
Possibly Chemistry thesises? Isn’t there a crystallography package?

**Comment by alex-konovalov** [comment]
@ruthhoffmann under "recent submissions" shown: 
- Finding "small' matrices P,Q such that PDQ = S by Robert Wainwright (2002) https://research-repository.st-andrews.ac.uk/handle/10023/15171

It seems they are digitising past theses now.

**Comment by alex-konovalov** [comment]
More from https://research-repository.st-andrews.ac.uk/handle/10023/6129:
- Andrew Cutting https://research-repository.st-andrews.ac.uk/handle/10023/15052
- Peter Campbell https://research-repository.st-andrews.ac.uk/handle/10023/15048
- Luis Descalco https://research-repository.st-andrews.ac.uk/handle/10023/15122

**Comment by alex-konovalov** [comment]
@ruthhoffmann not sure about chemistry, but indeed there are packages related to crystallography. Crawled maths theses, and found a couple of dozens missing!

**Comment by fingolfin** [comment]
With the website relaunch in PR #339 we dropped our bib, and I think that renders this issue moot.
