### ISSUE TITLE
Clearer installation instructions on webpage

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-system/GapWWW#16]
For the love of my life I could not figure out which of the two files InstPackages.sh or InstPackages32.sh should I run. I do not find the info on the webpage enough. In fact, from the text on the download page it is not even clear whether these files should be run or not. (I have a 64 bit machine, I also have installed multiarch for e.g. skype, but I have no idea if GAP is installed in 32 or 64 bit mode....)

I am not sure who uses GAP, and how much of an experts those people are, but it would be really nice to have a step-by-step tutorial on the webpage on how to install all feautures properly on linux, etc. 

PS. I just realized that most of these information are much better written down in the INSTALL file, and there is a link to this file from the Download page. Nevertheless, it would be nice if the "Linux" part of the download page would be a bit more clear, e.g. exactly which InstPackages file should one run (if at all), and maybe the phrase "step-by-step tutorial" could be written about the INSTALL file. Also, after downloading the script files on my machine they did not have the x right, so that should be written in the INSTALL file, as well (and not only into the script, as some people may not understand how scripts work). In particular, for me it was always confusing which information can be found exactly where....

Alternatively, there could just be one script file altogether in the main GAP directory which one should run and that would take the person through a complete step-by-step installation, maybe even interactively. (As an e.g., see how old Crunchbang linux had its own install script, or now Bunsenlabs). E.g. it could ask whether the user wants to compile all packages, or wants to pick which to compile, etc.

**Comment by hungaborhorvath** [comment]
Oh, and these scripts do not log anywhere, so there is really no way to know whether the packages were successfully compiled or not.

**Comment by alex-konovalov** [comment]
Thanks @hungaborhorvath - these are valid points. I am afraid there are way too many users who build GAP and do not compile packages, until they're trying to use something that needs e.g. IO and it does not work.

Just to check that we're speaking about the same page: do you mean http://www.gap-system.org/Releases/4.8.2.html or another page? 

IMHO 
```
Download one of the archives below, unpack it and run ./configure; make in the unpacked 
directory. Then put and run in the pkg subdirectory the shell script InstPackages.sh 
(for 32-bit builds on 64-bit machines, use InstPackages32.sh)
```
sounds almost clear, but I am looking at this text for several years, so of course I may not already see it (I said "almost" because I agree that for a non-expert it may not be obvious whether they have "32-bit builds on 64-bit machines" or not).

Practical advice:

* If someone would like to improve the text on the downloads page, please submit a PR changing this file: https://github.com/gap-system/GapWWW/blob/master/Releases/4.8.2.mixer. It will be used as a template for 4.8.3 release, so the new text will stay

* For changes in the INSTALL file, please edit https://github.com/gap-system/gap/blob/stable-4.8/INSTALL from the stable branch of the GAP repository. It would be also nice to convert it to INSTALL.md in markdown.

* For aspects of building packages, please use https://github.com/gap-system/gap/issues. GapWWW only reflects the state of the things...

**Comment by hungaborhorvath** [comment]
@alex-konovalov Yes, we are talking about the same page.

**Comment by alex-konovalov** [comment]
Just to note tha in PR https://github.com/gap-system/gap/pull/649 I've converted INSTALL to INSTALL.md inm Markdown and performed some cleanup.

**Comment by fingolfin** [comment]
Somewhat related: https://github.com/gap-system/gap/pull/740

**Comment by hungaborhorvath** [comment]
Is there a page where one could find all the necessary debian/ubuntu/etc packages to be installed in order to be able to compile gap (also for the development version), compile particular packages, etc? 

I probably could find all these information at different places, but I think it would be very helpful if _one_ webpage contained these information. Maybe in a manner of saying: for GAP one needs these packages, and additionally for package xgap one needs those, etc. And it would be especially helpful (for noobs like me) if instead of saying development package for this and this, the actual package name for debian/ubuntu/whatever would be there.

**Comment by alex-konovalov** [comment]
@hungaborhorvath the 'canonical' page would be "Installation" -> "Tools Needed": http://www.gap-system.org/Download/tools.html. Any suggestion regarding that are welcome. 

The problem with suggesting a precise list of packages is IMHO that it will decay with time. For example, @neunhoef did this for BOB installer, and some commands may already not work.

For Ubuntu, situation is not so bad, since we have Docker container for GAP and packages, and one could find appropriate `apt-get` calls at appropriate Dockerfiles:
* for GAP core: https://github.com/gap-system/gap-container/blob/master/Dockerfile
* for packages: https://github.com/gap-system/gap-docker-base/blob/master/Dockerfile

**Comment by hungaborhorvath** [comment]
@alex-konovalov I started looking at these dependencies and have #27 to try to update the page in a sensible way. I still have packages I did not manage to build, and I will continue to investigate. Sometimes I even found error messages with some packages, and I will try to contact the authors of those packages about them. 

However, let me mention that I believe that keeping the page http://www.gap-system.org/Download/tools.html updated is important, despite the fact that it needs continuous work. Further, in my opinion the _package_ _authors_ should help keeping this site updated, because ultimately the packages are their responsibility. Unfortunately, in some cases even the package authors do not clearly indicate what should be installed to properly configure and make their own packages (e.g. ````xgap```` was a pain to properly figure out, and the manual did not help at all, the tools website and the output of ````BuildPackages.sh```` did), and this could easily dissuade newcomers of using the particular package (or possibly even GAP for that matter).

**Comment by alex-konovalov** [comment]
It seems to be that #27 and #66 improved this, and I suggest to close this issue.

**Comment by fingolfin** [comment]
I don't think the instructions are great yet

**Comment by alex-konovalov** [comment]
That's true. As @angeldelriomateos wrote to me this week, his students

**Comment by fingolfin** [comment]
With the website relaunch in PR #339 I consider this issue resolved -- while the install instructions probably still have lots of room for improvement, the concrete things mentioned here are either resolved or not relevant anymore.

If someone has concrete suggestions for improvements or would like to point out specific things they find unclear in the instructions on the new website, then please open a new issue.
