### ISSUE TITLE
rebuild_Packages_dir.sh should first remove old YAML files

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#217]
... in case packages were dropped or renamed

**Comment by wilfwilson** [comment]
I've updated the title because I renamed this script last week 😬 

At one point during GAP Days, 'my' new WIP script for updating the website basically did this. In particular, the script called `git rm _Packages/*.html` before running `rebuild_Packages_dir.sh`. But I decided to remove it until I was sure it was the right thing to do.

It seems that, on the website, we do keep mentioning old packages that are dropped (ie the files at the bottom of https://www.gap-system.org/Packages/packages.html) - but this is a manually maintained list. So I think either we should automatically generate that list, or we should manually remove dropped/renamed packages.

The other less-important question for me is whether it's the `rebuild_Packages_dir.sh` file that should do this, or the new WIP update-website script; and if the latter, this raises the question of whether or not `rebuild_Packages_dir.sh` should even exist as a separate script.

**Comment by wilfwilson** [comment]
The `rebuild_packages_dir.sh` script has been removed; it is now redundant because of changes to GAP's `dev/releases/update-website.py` script (or at least it will be, once https://github.com/gap-system/gap/pull/4596 is merged, which is imminent).

In particular, `dev/releases/update-website.py` now empties the `_Packages` directory before re-populating it with the latest list of packages, so this issue is resolved. 

Issue #229 remains mostly unresolved, however.
