### ISSUE TITLE
Use GitHub Actions to deploy the master branch to https://gap-system.github.io/GapWWW

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/GapWWW#236]
~~There is a Travis configuration file that builds the Jekyll website. This doesn't work any more. We could do the same with GitHub Actions.~~

**Comment by fingolfin** [comment]
Indeed.

And with GitHub Actions, we could even set it to deploy the generated files into e.g. the `gh-pages` branch, but with a tweaked `_config.yml` (with correct `baseurl` value), so that the preview of the site at http://gap-system.github.io/GapWWW/ is actually useful

**Comment by fingolfin** [comment]
Just to clarify: the content of http://gap-system.github.io/GapWWW/ is currently derived from the master branch, but the problem is that the `_config.yml` there is written for a website deployed to the root directory, as is the case with our official website, while in that test location, it is in a subdir. An alternative solution for this would be to add yet another subdomain to `gap-system.org`, say `gh-pages.gap-system.org` or `test2.gap-system.org` with a CNAME DNS record pointing at GitHub; that also would work.

Of course we'd still not have the various "extra" files in there (like the Manuals), but still, I think it'd be useful

Oh, and in case getting St Andrews IT to add another subdomain is a chore, I could also point a subdomain of some other domain I own at it, that'd be a matter of <= 10 minutes work.

**Comment by fingolfin** [comment]
We now actually deploy the master branch immediately to www.gap-system.org, so this issue has become obsolete in a sense, or completed in another :-)
