### ISSUE TITLE
`SSL_ERROR_UNSUPPORTED_VERSION`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/GapWWW#238]
Today I have tried to click on the link [Archive of postings since December 2003](https://mail.gap-system.org/pipermail/forum/) on the page about the [GAP Forum Archive](https://www.gap-system.org/Doc/forumarchive.html).

The result was an error page with the code `SSL_ERROR_UNSUPPORTED_VERSION`. The page told me about a workaround (which worked to some extent), but it also says that this workaround might get disabled in future versions of Firefox, and that I should inform the owners of the web page about this problem.

**Comment by fingolfin** [comment]
That's a problem with the Mail server setup in St Andrews; I've reported this before to @ChrisJefferson @alex-konovalov @ruthhoffmann and they in turn told the IT staff about it, but apparently it's just the tip of a bigger iceberg, which is why it's still not resolved... *sigh*. We already discussed if we need to move infrastructure to another place, e.g. Kaiserslautern. We've gotta see.

**Comment by alex-konovalov** [comment]
Thanks. For now, Chrome may be easier to use (still with workarounds).

**Comment by fingolfin** [comment]
Note that the mail archives are currently not accessible anymore. This is because all outside access had to be blocked for security reasons. We are working on a solution

**Comment by fingolfin** [comment]
This should be fully resolved now. E.g. https://mail.gap-system.org/pipermail/forum/ redirects to https://www.gap-system.org/ForumArchive2/
