### ISSUE TITLE
Clarify relation between different package lists

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#265]
clarify relation between ...
1. https://www.gap-system.org/Packages/packages.html and 
2. https://gap-packages.github.io/

Note that the former links to the latter.

List 1 is the official list of distributed packages. List 2 is a list of package source repositories we happen to know about, including some which are not distributed. On the other hand, some distributed packages have no public repositories... Thus neither of the two lists is a subset of the other

**Comment by wilfwilson** [comment]
Today I updated https://gap-packages.github.io in several ways (see https://github.com/gap-packages/gap-packages.github.io/issues/14).

In particular, https://gap-packages.github.io now is a subset of the gap-system.org page:

As far as I could tell, there are now only three packages without a public development repository (AtlasRep, browse, and CTblLib), and so I felt like it made sense to mention these.

I also added some explanatory text at the top at the page.

In my opinion, this resolves the issue for https://gap-packages.github.io (although it may well become out of date, since, in part, it is manually updated).

However, https://www.gap-system.org/Packages/packages.html should still be clarified.

**Comment by fingolfin** [comment]
IMHO this is resolved with the new website design brought by PR #339
