### ISSUE TITLE
Mention DFG and NSF support in funding

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#82]
Add relevant projects from https://www.computeralgebra.de/ to https://www.gap-system.org/Contacts/funding.html . Also would be useful to indicate years.

**Comment by alex-konovalov** [comment]
Also add @hulpke's "Enabling Computer Algebra Use in the Undergraduate Abstract Algebra Curriculum" award https://www.nsf.gov/awardsearch/showAward?AWD_ID=0633333

**Comment by fingolfin** [comment]
I've resolved the top item (which amounts to acknowledging SFb TRR 195) so that part is done.

I don't know about the award for @hulpke but I assume if it was important to him he'd have added it years ago or asked us to add it, so I am closing this. That said, I'd be happy to assist in adding that aware of any other funding sources that benefited GAP if someone is interested in doing so.
