### ISSUE TITLE
Broken Links to GAP 3 manual on Webpage (since it is archived)

### ISSUE THREAD

**Issue by markuspf** [gap-system/GapWWW#99]
https://www.gap-system.org/Gap3/Manual3/C067S000.htm

for instance is broken

**Comment by alex-konovalov** [comment]
We no longer provide a web-hosted GAP 3 Manual, because people are constantly getting in web search results and this often caused a lot of confusion. Instead, GAP 3 manual may be downloaded as a tar.gz archive from https://www.gap-system.org/Gap3/Doc3/manual.html. If you will tell me where the above mentioned link is, I will fix the text there instead of making the link work.

**Comment by alex-konovalov** [comment]
This is a "wontfix" issue. I've checked that `grep -R Manual3 *` only returns results within the Gap3 directory.
